# This file was generated by yoyoengine. (https://github.com/yoyoengine/yoyoengine)
# Copyright (C) 2023-2026  Ryan Zmuda
#
# Licensed under the MIT license. See LICENSE file in the project root for details.

function(pack_resources INPUT_DIR OUTPUT_FILE TARGET_NAME)
    file(TO_CMAKE_PATH "${INPUT_DIR}" INPUT_DIR)
    file(GLOB_RECURSE RESOURCE_INPUT_FILES
        CONFIGURE_DEPENDS
        "${INPUT_DIR}/*"
    )

    add_custom_command(
        OUTPUT "${OUTPUT_FILE}"
        COMMAND $<TARGET_FILE:yep> "${INPUT_DIR}" "${OUTPUT_FILE}"
        DEPENDS yep ${RESOURCE_INPUT_FILES}
        COMMENT "Packing resources from ${INPUT_DIR} to ${OUTPUT_FILE}"
        VERBATIM
    )

    add_custom_target(${TARGET_NAME}
        DEPENDS "${OUTPUT_FILE}"
    )
endfunction()