# This file was generated by yoyoengine. (https://github.com/yoyoengine/yoyoengine)
# Copyright (C) 2023-2026  Ryan Zmuda
#
# Licensed under the MIT license. See LICENSE file in the project root for details.

function(pack_resources INPUT_DIR OUTPUT_FILE TARGET_NAME)
    file(TO_CMAKE_PATH "${INPUT_DIR}" INPUT_DIR)
    file(GLOB_RECURSE RESOURCE_INPUT_FILES
        CONFIGURE_DEPENDS
        "${INPUT_DIR}/*"
    )

    # The packer to run is published by yep's CMakeLists.txt via global
    # properties: the in-tree `yep` target for native builds, or a host-runnable
    # copy when cross-compiling (the in-tree binary would be a target-platform
    # executable that cannot run on the build host).
    get_property(_yep_packer     GLOBAL PROPERTY YEP_PACKER_COMMAND)
    get_property(_yep_packer_dep GLOBAL PROPERTY YEP_PACKER_DEPEND)
    if(NOT _yep_packer)
        # Fallback (e.g. yep.cmake included without yep's CMakeLists setup).
        set(_yep_packer "$<TARGET_FILE:yep>")
        set(_yep_packer_dep yep)
    endif()

    add_custom_command(
        OUTPUT "${OUTPUT_FILE}"
        COMMAND "${_yep_packer}" "${INPUT_DIR}" "${OUTPUT_FILE}"
        DEPENDS ${_yep_packer_dep} ${RESOURCE_INPUT_FILES}
        COMMENT "Packing resources from ${INPUT_DIR} to ${OUTPUT_FILE}"
        VERBATIM
    )

    add_custom_target(${TARGET_NAME}
        DEPENDS "${OUTPUT_FILE}"
    )
endfunction()